name: Deploy to IIS

on:
  workflow_dispatch:   # manually trigger karoge

jobs:
  build-deploy:
    runs-on: self-hosted   # ye tumhare IIS server runner pe chalega

    steps:
      - name: Restore
        run: |
          "C:\Program Files\dotnet\dotnet.exe" restore D:\IIS-Project-De-windows\QMSProject\clover.qms.web\clover.qms.web.sln

      - name: Build
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" D:\IIS-Project-De-windows\QMSProject\clover.qms.web\clover.qms.web.sln

      - name: Deploy
        run: |
          "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath="D:\IIS-Project-De-windows\QMSProject\clover.qms.web" -dest:contentPath="D:\IIS-Deploy\QMS"
